### PR TITLE
Use BooleanField(null=True) instead of NullBooleanField

### PR DESCRIPTION
**Pull request by ekmecic**
NullBooleanField causes a warning on Django 3.1.5 and will be deprecated in Django 4.0:

```
System check identified some issues:

WARNINGS:
djpaddle.Checkout.completed: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
        HINT: Use BooleanField(null=True) instead.
```

The suggested fix is to use BooleanField(null=True) instead, which is implemented here.

### CODE REVIEW

**Comment by FPurchess** [comment]
@ekmecic thanks! could you please add a migration for it as well?

**Comment by ekmecic** [comment]
I'm new to Django and package development in Python. I perused through the repo and tried the standard `python manage.py makemigrations` and some other tricks but had no luck. Could you please point me to the instructions? Thanks.

**Comment by ekmecic** [comment]
Got it working in the meantime. Ended up being a misconfiguration with how I was using Poetry to set up my development environment. Please take a look at the updated patch.

**Comment by FPurchess** [comment]
Hi @ekmecic, sorry for the late reply and good job! Thanks for your contribution!

**Pull request merged**
